spring:
  #아래 내용이 없어도 스프링부트에서 테스트돌릴 때 기본적으로 메모리 모드로 돌림
  #datasource:
  #  url: jdbc:h2:mem:test
  #  username: sa
  #  password:
  #  driver-class-name: org.h2.Driver

  datasource:
    url: ENC(NKZi7rJRYX4zLjQjjNTGzGT8KLpkYzI3hWlPRWe6Jh5M/MwKTXreUa/l9E+K4VcGwZK8kuJ9Dqg2lSEKUo7y7w==)
    username: ENC(58g4l7Vl04X2ManldaEe+JMa9aeQN68XpEyYMgUVcNI=)
    password: ENC(ZeEixrO88uEbVBfbi2/Unykmbj51D3CAUWMcnfrD13s=)
    driver-class-name: org.postgresql.Driver

  session:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000
        use_sql_comments: true
        open-in-view: false

      #FCM
      firebase-create-scoped: "https://www.googleapis.com/auth/firebase.messaging"
      firebase-multicast-message-size: 500

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  h2:
    console:
      enabled: true

  messages:
    basename: messages,errors

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: info

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: never

restemplate:
  readTimeout: 50000
  connectTimeout: 30000
  maxConnTotal: 100
  maxConnPerRoute: 5

jasypt:
  encryptor:
    bean: encryptorBean

token:
  secret: heardot-backend
  access-token-expiration-time: 900000  # 15분
  refresh-token-expiration-time: 1210500000 # 2주

my-pass: heardot*
firebase-sdk-path: firebase_service_key.json
project-id: heardot-671cc

